version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "80:3001" 
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bond_coffee
      DB_USER: postgres
      DB_PASSWORD: 11620
      SERVER_PORT: 3001
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: bond_coffee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11620
    volumes:

      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
volumes:
  pgdata:
