services:
  # Web Service (Frontend + Backend)
  - type: web
    name: bond-coffee
    env: node
    plan: free
    buildCommand: npm ci && npm run build:all
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: bond-coffee
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: bond-coffee-db
          property: connectionString

  # PostgreSQL Database
  - type: pgsql
    name: bond-coffee-db
    plan: free
    databaseName: bond_coffee
    user: bond_user