services:
  # PostgreSQL Database
  - type: postgres
    name: bond-coffee-db
    databaseName: bond_coffee
    user: bond_user
    plan: free

  # Web Service (Frontend + Backend)
  - type: web
    name: bond-coffee
    env: node
    plan: free
    buildCommand: npm ci && npm run build:all
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bond-coffee-db
          property: connectionString